dist: xenial
language: node_js
node_js:
- '10.2'
sudo: enabled
install:
- npm install --global gatsby-cli
- npm install
- mkdir data
- curl -vvv -H "$HEADER" "$DATA_ENDPOINT" > data/data.json
script:
- gatsby build --prefix-paths
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  local-dir: "./public"
  on:
    branch: master
  target-branch: gh-pages
  verbose: true
notifications:
  slack:
    secure: C8Ty5SBJMjLH9Wtb1H5Qqy5PbHeYcqrj+LydxcPqVph/o+91onK8/Tskg8rk1CAFj7QP/53VwslUgc42y9NkYfaTL8nPdMlTQ2JwukWZrHCAHm8LkgoC2req/PV1LaxYgmX023pogYflfBDus5NIWNOvIkQbL6X6XHnwTT+MIR9VlTkzCmb/PQyLcc+9ujIShMzP6krCCyBWAyPke3yyUytGFQhNNuoQDh47wax0MLpG5W4XP1VPPZIQus3wtRQVDfQc0qg14IPUCesXAmtXdXy5UqcAHUunK0/NzMiFW9JYM5M5sVdMkJ6JG5gaSEmoQ8IpiST6A8K9/W+3qCHINTNpF843iBVTmldFeesEhvMhxKFouyfjQZ152Pd1AUykf/nqASouUuxw8wV9YjWjzI9ZSJTqCoyrofLTdH5onW1Lo1yZUWQOQ7hRYkc1DGplHrf8tSk0tW2yOGUyk44T1PySWkHzQFcJUsh334h+L3ptQQPJ5TQl1rNn8EAI32VSff9yUatnA39xbJ7TN44AqfhdxKtUygDEhXFb56Z7OcHEoKhl7qz9kwALz/Qt8P2RkdkMq+MpSOzgT9Uqs/hoqdawOs8ckLKIem3ors3dsoYD9lQiEdxXomIgyN17Mqs5DoRm4uKAKOdeUP6IlNQq41AYEjTPuGxqZF11ncQ7/CY=
